name: Test and Notify
on:
  workflow_dispatch:
jobs:
  test-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout student repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: |
          npm test -- --coverage
          echo "Coverage report generated"
      

      - name: Send simple payload (Hello World) to application
        env:
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
          API_KEY: ${{ secrets.WEBHOOK_SECRET }}
          REPO_ID: ${{ github.repository_id }}
          REPO_NAME: ${{ github.repository }}
        run: |
          # Define a simple payload
          PAYLOAD="{\"message\": \"Hello World\", \"repository_id\": \"$REPO_ID\", \"repository_name\": \"$REPO_NAME\"}"


          # Send the data to the API endpoint
          HTTP_STATUS=$(curl -s -o response.txt -w "%{http_code}" \
            -X POST "$API_ENDPOINT" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $API_KEY" \
            -d "$PAYLOAD")

          # Check if the request was successful
          if [[ "$HTTP_STATUS" -ge 200 && "$HTTP_STATUS" -lt 300 ]]; then
            echo "Payload successfully sent! Response:"
            cat response.txt
          else
            echo "Failed to send payload. Status code: $HTTP_STATUS"
            cat response.txt
            exit 1
          fi
