name: Notify Updates Available
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  notify-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Notify application of updates
        env:
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }}github-actions/alert-update
          API_KEY: ${{ secrets.WEBHOOK_SECRET }}
          REPO_ID:   ${{ github.repository_id }}
          REPO_NAME: ${{ github.repository }}
          COMMIT_SHA: ${{ github.sha }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          curl -s \
            -X POST "$API_ENDPOINT" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $API_KEY" \
            -d "{
              \"repository_id\":   \"$REPO_ID\",
              \"repository_name\": \"$REPO_NAME\",
              \"commit\":          \"$COMMIT_SHA\",
              \"branch\":          \"$BRANCH_NAME\",
              \"updates_available\": true
            }"
