name: Send Test Results to Main Repo using API

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  report-results:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout student repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies and run tests
        run: |
          npm install
          # Adjust this command as needed. This example generates a coverage report.
          npm test -- --json --outputFile=test-results.json

      - name: Send test result to teacher repo
        run: |
          TEST_RESULTS="$(cat test-results.json | base64 | tr -d '\n')"
          
          # Bygg JSON med shell-escaping (OBS! fort gjort å trå feil med anførsler)
          JSON_STRING="{\"repo_name\": \"${{ github.repository }}\", \"commit_sha\": \"${{ github.sha }}\", \"test_results\": \"${TEST_RESULTS}\"}"
      
          gh api \
            repos/<YOUR_USERNAME_OR_ORG>/<TEACHER_REPO>/dispatches \
            --field event_type=student_test_results \
            --raw-field client_payload="$JSON_STRING"
        env:
          GITHUB_TOKEN: ${{ secrets.TEACHER_TOKEN }}

